### ISSUE TITLE
Uncaught TypeError : undefined, while closing file

### ISSUE THREAD

**Issue by honigbeutler123** [lkwdwrd/docblock-format-helper#1]
Hi, 
i am currently getting this error.

Uncaught TypeError: undefined is not a function

TypeError: undefined is not a function
    at ~/.atom/packages/docblock-format-helper/lib/docblockformatter.coffee:25:22
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:290:27)
    at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:45:58)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:468:18)
    at tabs-tab.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:216:24)
    at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

it happenes everytime i close an tab. doenst metter which suffix it has (.cpp, .txt, .qrc, .h ...) 

i am running this on archlinux ... i dont know if you need more informations just ask me :)

**Comment by lkwdwrd** [comment]
Hey all, there was a typo in the code throwing this on closing a file. I've been trying to add a couple of other features to the minor release, but with the reports, just pushed this up as a hotfix as 0.3.0. Go ahead and give it a try, if it continues, please let me know.
