### ISSUE TITLE
Uncaught TypeError: _this.subscriptions.remote is not a function

### ISSUE THREAD

**Issue by logarytm** [lkwdwrd/docblock-format-helper#2]
The following error pops up randomly when closing a tab with file of any type.

**Atom Version**: 1.0.15
**System**: Microsoft Windows 8.1
**Thrown From**: [docblock-format-helper](https://github.com/lkwdwrd/docblock-format-helper) package, v0.2.0
### Stack Trace

Uncaught TypeError: _this.subscriptions.remote is not a function

```
At /C:/Users/Olgierd/.atom/packages/docblock-format-helper/lib/docblockformatter.coffee:37

TypeError: _this.subscriptions.remote is not a function
  at C:\Users\Olgierd\.atom\packages\docblock-format-helper\lib\docblockformatter.coffee:25:22
  at Emitter.module.exports.Emitter.emit (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:290:27)
  at TextEditor.module.exports.Model.destroy (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:468:18)
  at Pane.module.exports.Pane.destroyActiveItem (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:443:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:617:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:656:21)
  at atom-workspace.atom.commands.add.core:close (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace-element.js:290:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Olgierd\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "jshint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.0.2
docblock-format-helper, v0.2.0
docblockr, v0.7.3
editorconfig, v1.2.0
emmet, v2.3.12
language-swig, v0.1.4
language-twig, v1.6.2
linter, v1.5.1
linter-jscs, v2.0.5
linter-jshint, v1.2.0
php-cs-fixer, v2.4.0

# Dev
No dev packages
```

**Comment by benohalloran** [comment]
this makes the package super annoying to use. I get the same error on fedora so it's not just windows.
1. close any file docblockr monitors/does things

**Atom Version**: 1.0.15
**System**: "Fedora release
**Thrown From**: [docblock-format-helper](https://github.com/lkwdwrd/docblock-format-helper) package, v0.2.0

### Stack Trace

Uncaught TypeError: _this.subscriptions.remote is not a function

```
At /home/ben/.atom/packages/docblock-format-helper/lib/docblockformatter.coffee:37

TypeError: _this.subscriptions.remote is not a function
  at /home/ben/.atom/packages/docblock-format-helper/lib/docblockformatter.coffee:25:22
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:290:27)
  at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:468:18)
  at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:443:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:617:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/usr/share/atom/resources/app.asar/src/workspace.js:656:21)
  at atom-workspace.atom.commands.add.core:close (/usr/share/atom/resources/app.asar/src/workspace-element.js:290:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -2:22.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:17.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:14.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:13.5.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -2:11.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:05.8.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -2:05.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:05.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:05.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:05.1.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -2:05.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:04.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -2:02.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.4.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:undo (atom-text-editor.editor.is-focused)
  7x -0:05.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "project-ring",
      "linter",
      "linter-clang"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.13
docblock-format-helper, v0.2.0
docblockr, v0.7.3
eclipse-keybindings, v0.8.0
language-ada, v1.1.0
language-fortran, v1.5.7
language-ocaml, v1.1.2
language-prolog, v0.10.0
language-rust, v0.4.5
language-x86, v0.1.0
minimap, v4.13.3

# Dev
No dev packages
```

**Comment by lkwdwrd** [comment]
This is the same issue as #1, pushed 0.3.0 just now which should address the issue. Please test and reply if it's still causing problems.
